spring:
  data:
    redis:
      host: redis-13568.c290.ap-northeast-1-2.ec2.cloud.redislabs.com
      port: 13568
      username: default
      password: Mp1IvsxURGgOJoKsHPzKDorBMUS6hk2V

  datasource:
    url: jdbc:h2:mem:test;
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
    show-sql: true

  sql:
    init:
      mode: always
